# Generated by Django 3.1.2 on 2020-10-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventureapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
