# Generated by Django 3.1.2 on 2020-10-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventureapp', '0002_remove_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
