# Generated by Django 3.0.3 on 2020-11-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventureapp', '0003_auto_20201023_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
