# Generated by Django 3.0.3 on 2020-11-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventureapp', '0004_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='post_image',
        ),
    ]
